INT-320:  README in Spanish
onfleet/pyonfleet pull request #25
Opened 2021-08-05 23:18 UTC by jcpmmx

Closes https://onfleet.atlassian.net/browse/INT-320
Closes https://onfleet.atlassian.net/browse/INT-302

- Adds `README.es.md`
- Modifies `README.md` and `README.zh-tw.md` retroactively for consistency, and links between them
- Adds `.gitignore`
- Fixes invalid JSON example in all readmes

2021-08-06 07:10 UTC, jmflaherty commented
Hey, @jcpmmx! Let me review this before merging. There are a few grammar errors in the Spanish version of the Readme that I can point out for you.

2021-08-06 13:05 UTC, jmflaherty requested changes
Thanks for doing this, @jcpmmx ! =D

Aside from these observations I would only discuss style, but I don't think we need to right now,  and as I've mentioned in a comment, there is nothing wrong with the one you used.

2021-08-06 14:56 UTC, jcpmmx commented on README.es.md
> +
Thanks a lot!

2021-08-06 14:57 UTC, jcpmmx commented on README.es.md
> +También tenemos la opción de no crear dicho archivo y, en cambio, proporcionar la clave para la API directamente en cada petición:
I only translated the original README verbatim, I haven't tried the tool yet...
Thoughts @jamesliupenn?

2021-08-06 15:02 UTC, jcpmmx commented on README.es.md
> +La API impone un límite de 20 peticiones por segundo, sumando las peticiones de todas las claves para la API disponibles en nuestra organización. [Aquí](https://docs.onfleet.com/reference#throttling)
Makes sense, it's been a while since I did docs in Spanish :D

2021-08-06 15:02 UTC, jcpmmx commented on README.es.md
> +Las respuestas de esta librería corresponden a instancias de [Response](https://2.python-requests.org//en/master/api/#requests.Response) de la librería `requests`.
👌

2021-08-06 15:04 UTC, jcpmmx commented on README.es.md
> +En la [documentación de la API](https://docs.onfleet.com/) están descritos qué recursos lo permiten.
Understood, valid point!
Changed it a bit though.

2021-08-06 15:04 UTC, jcpmmx commented on README.es.md
> +Para obtener un conductor según su ubicación, podemos utilizar la funcion `getByLocation`:
🔍

2021-08-06 15:05 UTC, jcpmmx commented on README.es.md
> +Para obtener un conductor según su ubicación, podemos utilizar la funcion `getByLocation`:
You mean the code samples?
I'll put them all in English, except for the comments.

2021-08-06 16:08 UTC, jamesliupenn commented on README.es.md
> +También tenemos la opción de no crear dicho archivo y, en cambio, proporcionar la clave para la API directamente en cada petición:
On the fly may be confusing from the original verbatim. The API key is either stored in a auth.json or passed in as a variable when initiating the Onfleet class.

2021-08-06 16:37 UTC, jcpmmx commented on README.es.md
> +También tenemos la opción de no crear dicho archivo y, en cambio, proporcionar la clave para la API directamente en cada petición:
I'll change the wording for English then 💪

2021-08-06 16:39 UTC, jcpmmx commented on README.es.md
> +La API impone un límite de 20 peticiones por segundo, sumando las peticiones de todas las claves para la API disponibles en nuestra organización. [Aquí](https://docs.onfleet.com/reference#throttling)
OK, fair point 👌

2021-08-06 16:40 UTC, jcpmmx commented on README.es.md
> +Estos son las ooperaciones disponibles para cada endpoint:
Thanks! I used to have 'endpoints', hence misgender 😬

2021-08-06 16:41 UTC, jcpmmx commented on README.es.md
> +```python
Solid points, thanks!

2021-08-06 21:21 UTC, jamesliupenn commented on README.es.md
> +Para obtener un conductor según su ubicación, podemos utilizar la funcion `getByLocation`:
Makes sense keeping it in English for parameters, I guess we can resolve this one?

2021-08-06 21:26 UTC, jamesliupenn commented on README.es.md
> +api = Onfleet(api_key="<llave_para_la_api>")  # Sin el archivo .auth.json
I would defer to using `api_key` instead

2021-08-06 21:27 UTC, jamesliupenn commented on README.es.md
> +getByLocation(queryParams="<datos_de_ubicacion>")
Same here, keeping it in English

2021-08-06 21:28 UTC, jamesliupenn commented on README.es.md
> +api.workers.create(body=datos)
Again, nitpicking here, we should keep this in accordance with the rest of the doc

2021-08-06 21:59 UTC, jamesliupenn commented on README.zh-tw.md
> +    "API_KEY": "<你的API金鑰>"
Similar to the Spanish version, let's make this `<your_API_key>` instead of the Chinese noun

2021-08-06 22:00 UTC, jamesliupenn commented on README.zh-tw.md
> +    "name": "A Swartz Test",
I think we updated this to John Driver? Might as well keep it in sync with other languages

2021-08-06 22:01 UTC, jamesliupenn requested changes
Minor nitpicking, let's revisit once modified

2021-08-06 22:07 UTC, jcpmmx commented on README.es.md
> +api = Onfleet(api_key="<llave_para_la_api>")  # Sin el archivo .auth.json
Makes sense, for consistency

2021-08-06 22:09 UTC, jcpmmx commented on README.es.md
> +getByLocation(queryParams="<datos_de_ubicacion>")
Gotcha, will do!

2021-08-06 22:11 UTC, jcpmmx commented on README.zh-tw.md
> +    "name": "A Swartz Test",
Done!

2021-08-06 22:21 UTC, jamesliupenn approved these changes
LGTM!

2021-08-09 11:50 UTC, jmflaherty requested changes
Thanks again, @jcpmmx . I made a couple comments.

2021-08-09 11:50 UTC, jmflaherty commented on README.es.md
> +Para obtener un conductor según su ubicación, podemos utilizar la funcion `getByLocation`:
That as well, @jcpmmx , but I meant using `driver` instead of `conductor` in this case.

2021-08-09 11:50 UTC, jmflaherty commented on README.es.md
> +También tenemos la opción de no crear dicho archivo y, en cambio, proporcionar la llave directamente en cada petición:
@jcpmmx , I see that you are confused about the usage of the `api_key`. The English readme says "on the fly", which means that you use it as you go with no extra setup through the auth file. See the [Onfleet class](https://github.com/onfleet/pyonfleet/blob/8dcc7a7d28add1daf2301659decf7bfb75540808/onfleet/onfleet.py#L18) and its constructor, which takes the `api_key` as a mandatory parameter to authenticate a session with which it will perform all requests. The param is only needed when instantiating this class as all requests will reuse the session that it creates.

2021-08-09 11:50 UTC, jmflaherty commented on README.es.md
> +La API impone un límite de 20 peticiones por segundo sumando las peticiones de todas las llaves de la organización. Más detalles [aquí](https://docs.onfleet.com/reference#throttling).
My suggestion to simplify with `entre` in replacement of `sumando las` is based on the [grammar complexity](https://www.scielo.cl/scielo.php?pid=S0718-48832013000200004&script=sci_arttext) of the text, where we explain what is done, adding to the effort that readers will have to do to understand the text when we can use a single term that means exactly what we are trying to communicate.

2021-08-09 16:10 UTC, jcpmmx commented on README.es.md
> +Para obtener un conductor según su ubicación, podemos utilizar la funcion `getByLocation`:
Cool, I unified the code samples in English

2021-08-09 20:07 UTC, jcpmmx commented on README.es.md
> +También tenemos la opción de no crear dicho archivo y, en cambio, proporcionar la llave directamente en cada petición:
Gotcha now, thank you for the explanation!

2021-08-09 20:10 UTC, jcpmmx commented on README.es.md
> +La API impone un límite de 20 peticiones por segundo sumando las peticiones de todas las llaves de la organización. Más detalles [aquí](https://docs.onfleet.com/reference#throttling).
Clearer now, gracias!

2021-08-10 16:30 UTC, jmflaherty approved these changes
Not a single error nor style smell 👌

2021-08-10 16:35 UTC, merged