[INT-1311][python-onfleet] Delivery Manifest Endpoint
onfleet/pyonfleet pull request #52
Opened 2024-05-27 18:20 UTC by lisandrobigi-onfleet

**Describe the solution**
New Onfleet Delivery Manifest API endpoint added as `getDeliveryManifest` method. In order to test the mentioned endpoints, the test file was updated using a dummy object.
https://docs.onfleet.com/reference/delivery-manifest

---

**Added**
- Added getDeliveryManifest endpoint
- Support to include Google Maps Directions API key, in this specific format Google <google_direction_api_key> in your HTTP header as X-API-KEY
- Support for optional query parameters `startDate` and `endDate`.
- Readme files were updated to support Workers POST method.

**Changed**

**Deprecated**

**Removed**

**Fixed**

**Security**

2024-05-28 22:14 UTC, danmenza approved these changes
Looks good, approved ✅

2024-05-29 17:34 UTC, kaiserawu requested changes
Just one little note to double check. Everything else seems good.

2024-05-29 17:34 UTC, kaiserawu commented on onfleet/request.py
> +                'path': f'providers/manifest/generate?hubId={workerId}&workerId={hubId}',
Are the `workerId` and `hubId` in the right places? They look like they're swapped here.

2024-05-29 19:17 UTC, lisandrobigi-onfleet commented on onfleet/request.py
> +                'path': f'providers/manifest/generate?hubId={workerId}&workerId={hubId}',
Yes, good catch! Thanks Kai

2024-05-29 19:33 UTC, kaiserawu approved these changes
LGTM!

2024-06-03 17:10 UTC, merged